# Generated by Django 2.1.7 on 2019-04-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs2150',
            name='letterGrade',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
